### ISSUE TITLE
Singularity 1.8.2 - psmdtemp

### ISSUE THREAD

**Issue by mitchellxh** [miac-research/psmd#8]
Thanks so much for making psmd container compatible! 

I am running into an issue with the psmdtemp folder. I use the "-t" flag, but I'm not seeing the psmdtemp where I believe it should spawn (the current working directory). Additionally, on rerun, it will detect a psmdtemp folder and forces me to use the "-c" flag. I will paste my command below, but can you confirm where the psmdtemp folder is being saved?

DWI=/user/home/imaging

singularity exec -B $DWI:/base psmd_1.8.2.sif psmd.sh -p /base/dwi.nii.gz -b /base/dwi.bval -r /base/dwi.bvec -s /base/skeleton_mask_2019.nii.gz -c -t -g -e 700 -q

**Comment by marcoduering** [comment]
Hello! This is interesting. Can you please try the following: Add a `-B $(pwd)` to your command to explicitly make the directory in which you run the command (working directory) available within the container. The psmdtemp should then be saved in the working directory.

I will also think about how to handle this in a better way.
